"""init

Revision ID: acc117f2e93e
Revises: 
Create Date: 2026-04-19 22:08:22.737823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'acc117f2e93e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_fragment', sa.Text(), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module'))
    )
    op.create_index(op.f('ix_module_code'), 'module', ['code'], unique=True)
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('diary',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('ai_processed_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'parsing', 'parsed', 'failed', name='diary_status'), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_diary_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diary')),
    sa.UniqueConstraint('user_id', 'date', name='uq_diary_user_date')
    )
    op.create_index(op.f('ix_diary_date'), 'diary', ['date'], unique=False)
    op.create_index(op.f('ix_diary_status'), 'diary', ['status'], unique=False)
    op.create_index(op.f('ix_diary_user_id'), 'diary', ['user_id'], unique=False)
    op.create_table('action_log',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('diary_id', sa.BigInteger(), nullable=True),
    sa.Column('module_code', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', 'rolled_back', name='action_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diary_id'], ['diary.id'], name=op.f('fk_action_log_diary_id_diary'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_action_log_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_log'))
    )
    op.create_index(op.f('ix_action_log_diary_id'), 'action_log', ['diary_id'], unique=False)
    op.create_index(op.f('ix_action_log_module_code'), 'action_log', ['module_code'], unique=False)
    op.create_index(op.f('ix_action_log_user_id'), 'action_log', ['user_id'], unique=False)
    op.create_table('ai_call_log',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('diary_id', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('success', 'parse_failed', 'api_error', name='ai_call_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diary_id'], ['diary.id'], name=op.f('fk_ai_call_log_diary_id_diary'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_ai_call_log_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_call_log'))
    )
    op.create_index(op.f('ix_ai_call_log_diary_id'), 'ai_call_log', ['diary_id'], unique=False)
    op.create_index(op.f('ix_ai_call_log_prompt_hash'), 'ai_call_log', ['prompt_hash'], unique=False)
    op.create_index(op.f('ix_ai_call_log_user_id'), 'ai_call_log', ['user_id'], unique=False)
    op.create_table('event',
    sa.Column('diary_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('module_code', sa.String(length=64), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('ai_processed_text', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diary_id'], ['diary.id'], name=op.f('fk_event_diary_id_diary'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_event_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    op.create_index(op.f('ix_event_diary_id'), 'event', ['diary_id'], unique=False)
    op.create_index(op.f('ix_event_module_code'), 'event', ['module_code'], unique=False)
    op.create_index(op.f('ix_event_user_id'), 'event', ['user_id'], unique=False)
    op.create_table('profile_section',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('module_code', sa.String(length=64), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('privacy', sa.Enum('public', 'ai_only', 'private', name='profile_privacy'), nullable=False),
    sa.Column('updated_by_event_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_event_id'], ['event.id'], name=op.f('fk_profile_section_updated_by_event_id_event'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_profile_section_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_section')),
    sa.UniqueConstraint('user_id', 'module_code', name='uq_profile_user_module')
    )
    op.create_index(op.f('ix_profile_section_module_code'), 'profile_section', ['module_code'], unique=False)
    op.create_index(op.f('ix_profile_section_user_id'), 'profile_section', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_section_user_id'), table_name='profile_section')
    op.drop_index(op.f('ix_profile_section_module_code'), table_name='profile_section')
    op.drop_table('profile_section')
    op.drop_index(op.f('ix_event_user_id'), table_name='event')
    op.drop_index(op.f('ix_event_module_code'), table_name='event')
    op.drop_index(op.f('ix_event_diary_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_ai_call_log_user_id'), table_name='ai_call_log')
    op.drop_index(op.f('ix_ai_call_log_prompt_hash'), table_name='ai_call_log')
    op.drop_index(op.f('ix_ai_call_log_diary_id'), table_name='ai_call_log')
    op.drop_table('ai_call_log')
    op.drop_index(op.f('ix_action_log_user_id'), table_name='action_log')
    op.drop_index(op.f('ix_action_log_module_code'), table_name='action_log')
    op.drop_index(op.f('ix_action_log_diary_id'), table_name='action_log')
    op.drop_table('action_log')
    op.drop_index(op.f('ix_diary_user_id'), table_name='diary')
    op.drop_index(op.f('ix_diary_status'), table_name='diary')
    op.drop_index(op.f('ix_diary_date'), table_name='diary')
    op.drop_table('diary')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_module_code'), table_name='module')
    op.drop_table('module')
    # ### end Alembic commands ###
